guard 'rspec', cmd: 'rspec' do
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})     { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^lib/maze.rb$})     { |m| "spec/gridded_maze_spec.rb" }
  watch(%r{^lib/point.rb$})     { |m| "spec/gridded_maze_spec.rb" }
  watch(%r{^lib/vector.rb$})     { |m| "spec/gridded_maze_spec.rb" }
  watch('spec/spec_helper.rb')  { "spec/" }
end
