#!/bin/sh

cd `dirname $0`

exec >> /var/log/robot.log
exec 2>> /var/log/robot.err

pidfile=/var/run/robot.pid

if [ ! \( -f $pidfile \) ]; then
    echo "Couldn't find pid file"
    exit
fi
if [ ! \( -d /proc/`cat $pidfile` \) ]; then
    echo "Not running"
    exit
fi
echo "Stopping robot..."
kill `cat $pidfile`
kill -H `cat $pidfile` # this should kill it in sleep
kill -ALRM `cat $pidfile` # this should kill it in sleep
sleep 2
if [ ! \( -d /proc/`cat $pidfile` \) ]; then
    exit
fi
echo "Killing with -9"
kill -9 `cat $pidfile`
;;
